# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: New York City Marathon
email: admin@nycitymarathon.us
description: >- # this means to ignore newlines until "baseurl:"
  The 45th New York City Marathon 2018 will take place on the 4th November, 2018. 
  Find more details about the New York City Marathon 2018 including live Streaming Channels, Who Is Running,
  Route, Map and How to watch live online without cable.
logo: 'assets/images/NYCityMaraThon2018.png'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nycitymarathon.us/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title:output_ext
# ampdir: /amp/
publisher: https://plus.google.com/b/115112539419367993402/
github_username:  jekyll
analytics: 'UA-120674991-1' #Enter your Google Analytics Tracking Code
disqus: ny-city-marathon
author:
  name: Abu Zafor

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-compose
  - jekyll-assets
  - jekyll-archives
  - jekyll-redirect-from
  #- amp-jekyll
  - jekyll-twitter-plugin


jekyll-mentions:
  base_url: https://twitter.com

toc:
  min_level: 2 # default: 1
  max_level: 5 # default: 6

main_nav:
  Home: /
  About: '/about.html'
  Contact: '/contact.html'
  Live Stream: '#how-to-watch-new-york-city-marathon-2018-live-online-without-cable'

primary_nav:
  Overview: '#new-york-city-marathon-2018-quick-overview'
  Start Time: '#tcs-new-york-city-marathon-2018-start-time'
  Live Stream: '#how-to-watch-new-york-city-marathon-2018-live-online-without-cable'
  TV Channel: '#tcs-new-york-city-marathon-tv-channels'

social_nav:
  Facebook: https://facebook.com
  Twitter: https://twitter.com
  Google+: https://plus.google.com
  Pinterest: https://pinterest.com

# source_maps: true # false on JEKYLL_ENV=production
# destination: "/assets"
# compression: false # true on JEKYLL_ENV=production
# gzip: false
# defaults:
#    js: { integrity: false } # true on JEKYLL_ENV=production
#   css: { integrity: false } # true on JEKYLL_ENV=production
#   img: { integrity: false } # true on JEKYLL_ENV=production
# caching:
#   path: ".jekyll-cache/assets"
#   type: file # Possible values: memory, file
#   enabled: true
# --
# Assets you wish to always have compiled.
#   This can also be combined with raw_precompile which
#   copies assets without running through the pipeline
#   making them ultra fast.
# --
# precompile: []
# raw_precompile: [
#   #
# ]
# --
# baseurl: whether or not to append site.baseurl
# destination: the folder you store them in on the CDN.
# url: the CDN url (fqdn, or w/ identifier).
# --
# cdn:
#   baseurl: false
#   destination: false
#   url: null
# --
# These are all default. No need to add them
#   Only use this if you have more.
# --
# sources:
#   - assets/css
#   - assets/fonts
#   - assets/images
#   - assets/videos
#   - assets/javascript
#   - assets/video
#   - assets/image
#   - assets/img
#   - assets/js
#   - _assets/css
#   - _assets/fonts
#   - _assets/images
#   - _assets/videos
#   - _assets/javascript
#   - _assets/video
#   - _assets/image
#   - _assets/img
#   - _assets/js
#   - css
#   - fonts
#   - images
#   - videos
#   - javascript
#   - video
#   - image
#   - img
#   - js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - ".DS_Store"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "yarn-error.log"
  - "pg"
  - "upload.sh"
  - "gulpbak.js"
  - "package-lock.json"
